<h1><center>Comparison of logistic regression in sklearn and statsmodels</center></h1>
<center>Rotten Tomatoes Group</center>

## 1. Setup
Using a sample binary classification dataset from sklearn, we can compare the API calls of each logistic regression function. 

First, load the breast cancer sample dataset. 

In [105]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
from statsmodels.discrete.discrete_model import Logit

In [106]:
data = load_breast_cancer()

In [107]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [108]:
features = data['data']
y = data['target']

In [109]:
features.shape

(569, 30)

In [110]:
y.shape

(569,)

In [111]:
np.unique(y)

array([0, 1])

In [112]:
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

We'll simulate our regression problem by picking a single, continuous X feature and using that to predict our binary outcome variable. Let's use "mean radius" to predict a diagnosis of breast cancer. 

In [113]:
mean_radius = features[:, 1]
mean_radius.shape

(569,)

In [114]:
y.shape

(569,)

In [115]:
## Best practice would be to do a train/test split here, but it's not necessary for a demo. 

Some common things you would want to do with a logistic regression function would be: 
1. Fit your training data 
2. See model performance statistics, like a confusion matrix and accuracy score 
3. Predict outcome variable for test set 

How easy are each of these tasks with the library? 

## 2. Logistic regression with sklearn 

In [116]:
try: 
    clf = LogisticRegression(random_state=0).fit(mean_radius, y)
except Exception as e:
    print(e)

Expected 2D array, got 1D array instead:
array=[10.38 17.77 21.25 20.38 14.34 15.7  19.98 20.83 21.82 24.04 23.24 17.89
 24.8  23.95 22.61 27.54 20.13 20.68 22.15 14.36 15.71 12.44 14.26 23.04
 21.38 16.4  21.53 20.25 25.27 15.05 25.11 18.7  23.98 26.47 17.88 21.59
 21.72 18.42 25.2  20.82 21.58 21.35 24.81 20.28 21.81 17.6  16.84 18.66
 14.63 22.3  21.6  16.34 18.24 18.7  22.02 18.75 18.57 21.59 19.31 11.79
 14.88 20.98 22.15 13.86 23.84 23.94 21.01 19.04 17.33 16.49 21.31 14.64
 24.52 15.79 16.52 19.65 10.94 16.15 23.97 18.   20.97 15.86 24.91 26.29
 15.65 18.52 21.46 24.59 21.8  15.24 24.02 22.76 14.76 18.3  19.83 23.03
 17.84 19.94 12.84 19.77 24.98 13.43 20.52 19.4  19.29 15.56 18.33 18.54
 19.67 21.26 16.99 20.76 19.65 20.19 15.83 21.53 15.76 16.67 22.91 20.01
 10.82 17.12 20.2  10.89 16.39 17.21 24.69 18.91 16.39 25.12 13.29 19.48
 21.54 13.93 21.91 22.47 16.67 15.39 17.57 13.39 11.97 18.05 17.31 15.92
 14.97 14.65 16.58 18.77 15.18 17.91 20.78 20.7  15.34 13.08 15.34 17.94
 20.

I found it interesting that you have to have 2D array of input variables. It cannot handle a 1D numpy case gracefully, and throws an exception. 

In [117]:
mean_radius = mean_radius.reshape(-1, 1)
mean_radius.shape

(569, 1)

In [118]:
clf = LogisticRegression(random_state=0).fit(mean_radius, y)

In [119]:
# ACCURACY
# There are two ways of calculating model accuracy - 
# a built in class attribute...
clf.score(mean_radius, y)

0.7047451669595782

In [120]:
# ... or a helper function. 
preds = clf.predict(mean_radius)
accuracy_score(y, preds)

0.7047451669595782

In [121]:
# CONFUSION MATRIX
confusion_matrix(y, preds) 

array([[ 91, 121],
       [ 47, 310]])

Two thoughts here are: 
1. It's not immediately clear what the rows/columns of the confusion matrix mean, and 
2. It would be nice to have all model performance statistics as attributes on the LogisticRegression class. 

In [122]:
# PREDICT OUTCOME VARIABLE 
clf.predict(mean_radius)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,

## 3. Logistic regression with statsmodels

In [123]:
"""
CONFUSED ATTEMPT AT TRAINING: API changed!

mean_radius.reshape(-1).shape

# Create the formula string 
formula = "Target ~ mean_radius"
mean_radius = mean_radius.reshape(-1)
trainingdata = pd.DataFrame({
    'Target': y,
    'mean_radius': mean_radius
})

trainingdata.head()

This method of specifying a formula call, like in R, is now available through the attribute 
Logit.from_formula()
"""

'\nCONFUSED ATTEMPT AT TRAINING: API changed!\n\nmean_radius.reshape(-1).shape\n\n# Create the formula string \nformula = "Target ~ mean_radius"\nmean_radius = mean_radius.reshape(-1)\ntrainingdata = pd.DataFrame({\n    \'Target\': y,\n    \'mean_radius\': mean_radius\n})\n\ntrainingdata.head()\n\nThis method of specifying a formula call, like in R, is now available through the attribute \nLogit.from_formula()\n'

In [124]:
# Build the model
clf = Logit(y, mean_radius).fit()

Optimization terminated successfully.
         Current function value: 0.680047
         Iterations 4


In [125]:
# PREDICTIONS
# If you want to pass a different outcome vector (such as a test set), you can, 
# but by default the class will use the outcome vector you used at train time. 
preds = clf.predict()
preds[0:5]

array([0.54274549, 0.57283519, 0.58683384, 0.58334638, 0.55892246])

In [126]:
# ACCURACY SCORE
try:
    clf.score()
except Exception as e:
    print(e)

'LogitResults' object has no attribute 'score'


It was confusing from [the documentation](https://www.statsmodels.org/stable/generated/statsmodels.discrete.discrete_model.Logit.score.html#statsmodels.discrete.discrete_model.Logit.score) how we were supposed to pull the accuracy score. We were not sure where to pull the "params" argument from, or what that meant. [the documentation for the main Logit class](https://www.statsmodels.org/stable/generated/statsmodels.discrete.discrete_model.Logit.html#statsmodels.discrete.discrete_model.Logit) did not specify that "params" was an attribute of the trained model object. 

In [127]:
try:
    Logit(y, mean_radius).score()
except Exception as e:
    print(e)

score() missing 1 required positional argument: 'params'


In [128]:
clf.params

array([0.01651256])

In [129]:
Logit(y, mean_radius).score(clf.params)[0]

4.547473508864641e-13

The documentation for the "score" was difficult to understand. It was targeted to an audience with an advanced statistics background. 

In [130]:
# CONFUSION MATRIX
clf.pred_table()

array([[  0., 212.],
       [  0., 357.]])

One thing we noticed while building this model is that the model API has changed over time. This [blog post](https://data.library.virginia.edu/logistic-regression-four-ways-with-python/) has a pretty different specification for the logistic regression call, which is closer to R syntax (specifying a formula string). The [new documentation](https://www.statsmodels.org/stable/generated/statsmodels.discrete.discrete_model.Logit.html#statsmodels.discrete.discrete_model.Logit) is closer to scikit-learn where you just specify an array of predictor and outcome variables. 

One thing we didn't like was that the new API documentation didn't have examples of how to set up the model. We were not sure if we needed to call ".fit()" to train the model. 

## 4. Package performance 
Time the model training for each package and see if there is a computational difference. 

In [131]:
import time

In [132]:
# sklearn
tic = time.perf_counter()
LogisticRegression(random_state=0).fit(mean_radius, y)
toc = time.perf_counter()

print(f"Sklearn model trained in {toc - tic:0.4f} seconds.")

Sklearn model trained in 0.0377 seconds.


In [133]:
# statsmodels
tic = time.perf_counter()
Logit(y, mean_radius).fit()
toc = time.perf_counter()

print(f"Statsmodels model trained in {toc - tic:0.4f} seconds.")

Optimization terminated successfully.
         Current function value: 0.680047
         Iterations 4
Statsmodels model trained in 0.0090 seconds.


Scale this up to train the model 10x and better protect against random state of your machine.

In [134]:
# sklearn
tic = time.perf_counter()
for i in range(10):
    LogisticRegression(random_state=0).fit(mean_radius, y)
toc = time.perf_counter()

print(f"Sklearn model trained in {toc - tic:0.4f} seconds.")

Sklearn model trained in 0.1858 seconds.


In [135]:
# statsmodels
tic = time.perf_counter()
for i in range(10):
    Logit(y, mean_radius).fit()
toc = time.perf_counter()

print(f"Statsmodels model trained in {toc - tic:0.4f} seconds.")

Optimization terminated successfully.
         Current function value: 0.680047
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.680047
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.680047
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.680047
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.680047
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.680047
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.680047
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.680047
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.680047
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.680047
  

Finding - statsmodels is faster in model training. 

## 5. Summary

1. We were more impressed with scikit-learn's documentation and examples. 
2. Both packages could easily perform the regression we're planning. 
3. Statsmodels did train a little faster than scikit-learn. 

For our project, because we don't have a very computationally-intensive model, we will likely go with scikit-learn. 